### ISSUE TITLE
Move raknet handling into an independent library

### ISSUE THREAD

**Issue by Techcable** [minecrafter/voxelwind#2]
Raknet handling should be in a independent library so other code can reuse it.
It should ideally be in a separate repository (and possibly organization) but a maven module would work too.

Also, shouldn't your accelerated encryption/decryption code be in a separate library too?

**Comment by minecrafter** [comment]
I'm focused on making a working server, not dicing Voxelwind into reusable bits.

The accelerated code for encryption and compression [is already separate, however](https://github.com/minecrafter/voxelwind-natives).

**Comment by TheDiamondYT1** [comment]
Why would it be a whole organization for a simple library!?
