### ISSUE TITLE
Chunk storage separation

### ISSUE THREAD

**Issue by minecrafter** [minecrafter/voxelwind#24]
Voxelwind should provide flexible support for custom chunk storage. This means a lot of interesting possibilities:

* **Copy on write levels**: great for hosting many minigame levels on one server.
* **Remote chunk loading**: load chunks from S3 or similar for a player world (ala LEET or Minecraftly) or for zero-restart map updates for minigames.
* **Custom map formats**: Voxelwind provides a few but you can make your own.

**Comment by minecrafter** [comment]
Partially implemented.

`LevelChunkManager` is a caching chunk provider that asks a `ChunkProvider` for the chunk if required.

**Comment by Techcable** [comment]
Tux, I'm really glad you're making this project.
I've always doubted pocket edition, but with you making this server, I think it's the future.

**Comment by minecrafter** [comment]
Already done, but needs API exposure.
