### ISSUE TITLE
Sometimes you can't pick up items such a dirt

### ISSUE THREAD

**Issue by stayandwait** [minecrafter/voxelwind#30]
If you break to many blocks sometimes you can't pick them up.

**Comment by minecrafter** [comment]
This has more to do with my (still somewhat faulty) handling of entity spawn packets.

**Comment by stayandwait** [comment]
The item drops don't show after breaking a block. They did in the past. I know I am picking up the blocks though.

**Comment by minecrafter** [comment]
I found the issue, working on resolving it.
