### ISSUE TITLE
Items in your hotbar don't show when your inventory is closed

### ISSUE THREAD

**Issue by stayandwait** [minecrafter/voxelwind#31]
When my inventory is closed in Minecraft Windows 10 edition it will appear that I don't have anything in my hotbar, but when my inventory is open I can see the dirt I picked up previously. See photos attached.

![2016-09-19_1811](https://cloud.githubusercontent.com/assets/15825041/18650770/dfe1762c-7e94-11e6-9ba3-0ff3c0a786c2.png)

![2016-09-19_1812](https://cloud.githubusercontent.com/assets/15825041/18650773/e36ad07c-7e94-11e6-8937-17819c2f75b7.png)

**Comment by minecrafter** [comment]
Windows 10 edition is just a pot of bad luck when it comes to inventories. Everything works fine with the iOS version.

I'm out of it today because of sinusitis but I'll take a peek at it next week once I have my new computer set up and ready to go.

**Comment by stayandwait** [comment]
It's simple to say that it works in iOS, but when i'm looking for bugs, I prefer the Windows 10 edition when it comes to making print screens. It makes things easier being on a PC because that is where the voxel client is also.

**Comment by TheDiamondYT1** [comment]
How did you join on windows 10? It shows me 3 ip addresses and none let me connect. I can join on ios.

Heres what ipconfig shows:

![image](https://cloud.githubusercontent.com/assets/14148452/18808360/e4a2e7d8-8257-11e6-9794-c098bafaebd4.png)

**Comment by Tee7even** [comment]
@TheDiamondYT1 umm... **Maybe** "localhost"?

**Comment by Pub4Game** [comment]
This is a bug associated DROP_ITEM_PACKET when you close the inventory, the client throws the item of the cell. As one of the solutions used in Nukkit (maybe wrong) [check ](
https://github.com/Nukkit/Nukkit/blob/master/src/main/java/cn/nukkit/Player.java#L2619-L2621)

**Comment by MiniDigger** [comment]
@TheDiamondYT1 someone told me that on irc:
> CRBairdUSA	@MiniDigger you can try the solution for nukkit?
> CRBairdUSA	@MiniDigger Configure your server to another port (29132, for example);
> CRBairdUSA	Type (once) in command line: CheckNetIsolation LoopbackExempt -a -n="Microsoft.MinecraftUWP_8wekyb3d8bbwe"
> CRBairdUSA	Run your Windows 10 Minecraft add new server (IP:localhost, port:29132) and connect to server.
that worked for me.

**Comment by stayandwait** [comment]
@TheDiamondYT1 You use a separate computer or server to host your world and make sure the client isn't using the same computer the host is using. That as much works for me.

**Comment by minecrafter** [comment]
I finally have a working Windows environment to test this on.

**Comment by minecrafter** [comment]
**Reproduced**. This doesn't have a particularly easy solution, however. We'll see...
