### ISSUE TITLE
Players cannot see each other`

### ISSUE THREAD

**Issue by stayandwait** [minecrafter/voxelwind#32]
# Report Summary.
You're unable to see other players. Is this a bug or is this just something that hasn't been fully implemented yet?

# An example:
I can see when a client removed and places a block but I cannot see the specific player.

**Comment by minecrafter** [comment]
Not implemented yet.

I should mention that this is clearly spelled out on the README: Voxelwind aims to be a comprehensive implementation of MCPE, **but is currently incomplete and lacks several important features**.

**Comment by stayandwait** [comment]
Ok good thing I asked.
