### ISSUE TITLE
Allow (and fix) wrong yaw values, send from the client

### ISSUE THREAD

**Issue by MiniDigger** [minecrafter/voxelwind#33]
http://hastebin.com/edafayokih.md

it looks like the client does not care much about the yaw values getting higher then 360 or lower then 0 like its expected to be here https://github.com/minecrafter/voxelwind/blob/master/api/src/main/java/com/voxelwind/api/util/Rotation.java#L83
I am using the win10 clients, if that does matter. 
server should allow those values, apply some modulo magic and only save the fixed values.

**Comment by minecrafter** [comment]
Mojang why must you do this to me

**Comment by MiniDigger** [comment]
I don't know if we should save the bad values. just return val%360 and save that.

**Comment by minecrafter** [comment]
I don't have the time to seriously verify this time for the moment.
