### ISSUE TITLE
Get disconected after a few seconds

### ISSUE THREAD

**Issue by TheDiamondYT1** [minecrafter/voxelwind#34]
On iOS 0.15.4 latest Voxelwind build i disconect after a few seconds and i cant chat in the time im connected.

Log: http://paste.ubuntu.com/23224527/

**Comment by hugmanrique** [comment]
Were you the only one connected to the server? If this was the case, the issue might be when sending the players the McpePlayerList packet with them inside the array of new players.

If not, it may be because the packet is too large (Look at the last line of code)

**Comment by TheDiamondYT1** [comment]
Just me, its a local server

**Comment by minecrafter** [comment]
Resolved for now, there are indeed problems with the player list packet.
