### ISSUE TITLE
TravisCI Builds

### ISSUE THREAD

**Issue by hugmanrique** [minecrafter/voxelwind#40]
It would be neat to get builds automatically built by TravisCI or a similar build system.

Nvm, I found that you have a jenkins server

**Comment by minecrafter** [comment]
Yes, we do (currently) use Jenkins.

**Comment by minecrafter** [comment]
You should ask questions on [the forums](https://forums.voxelwind.com) or [Gitter](https://gitter.im/minecrafter/voxelwind).
